bcp_profile:
  target: dev 
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      database: bcp_staging_db
      server: (local)
      port: 1433
      schema: dbo
      authentication: ActiveDirectoryIntegrated
      trust_cert: True