bcp_profile:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: (local)
      port: 1433
      database: bcp_staging_db
      schema: dbo
      user: dbt_sqlserver
      password: dbt_sqlserver
      TrustServerCertificate: True